### POST make json
POST http://{{host}}:{{port}}/json
Content-Type: application/json

{
  "type": "object",
  "row_count": 2,
  "fields": [
    "{\"name\":\"t\",\"function\":\"uint8\",\"params\":null}",
    "{\"name\":\"h\",\"function\":\"uint8\",\"params\":null}"
  ],
  "indent": true
}
### Response
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Wed, 12 Nov 2025 03:18:38 GMT
Content-Length: 28

{
    "t": 217,
    "h": 1
}
###