### POST openai-simulator
POST http://{{host}}:{{port}}/openai-simulator/v1/chat/completions
Content-Type: application/json

{
  "model": "2024-0618-sensenova",
  "stream": true,
  "messages": [
    {
      "role": "system",
      "content": "test111"
    },
    {
      "role": "user",
      "content": "hello world"
    }
  ]
}

### Response
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/event-stream
Date: Sun, 04 Aug 2024 09:56:25 GMT
Transfer-Encoding: chunked

Response code: 200 (OK); Time: 3ms (3 ms)

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":0,"delta":{"content":"This is message 0: content: [1903] F150 Ffv  4wd-Passenger car medium-Lancia-Methanol-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":1,"delta":{"content":"This is message 1: content: [1963] Gti-Sport utility vehicle-Honda-Gasoline-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":2,"delta":{"content":"This is message 2: content: [1922] Pacifica Awd-Passenger car heavy-Land Rover-CNG-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":3,"delta":{"content":"This is message 3: content: [1989] Sportage 2wd-Van-Lada-Ethanol-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":4,"delta":{"content":"This is message 4: content: [1973] Ferrari F141-Passenger car mini-Daewoo-CNG-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":5,"delta":{"content":"This is message 5: content: [1950] Legacy Wagon Awd-Passenger car light-Aston Martin-Diesel-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":6,"delta":{"content":"This is message 6: content: [1972] K15 Silverado Hybrid 4wd-Passenger car mini-Jaguar-Ethanol-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":7,"delta":{"content":"This is message 7: content: [1935] Clk350-Passenger car heavy-Bentley-CNG-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":8,"delta":{"content":"This is message 8: content: [1908] Is 250-Van-Ligier-Diesel-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":9,"delta":{"content":"This is message 9: content: [1928] Expedition 2wd-Passenger car medium-Corvette-LPG-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":10,"delta":{"content":"This is message 10: content: [1975] Ml500-Passenger car heavy-Datsun-Electric-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":11,"delta":{"content":"This is message 11: content: [1991] Is 250 Awd-Passenger car mini-Aston Martin-Diesel-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":12,"delta":{"content":"This is message 12: content: [1908] Legacy Wagon Awd-Van-Lincoln-LPG-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":13,"delta":{"content":"This is message 13: content: [1925] Sequoia 4wd-Passenger car mini-Vauxhall-Gasoline-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":14,"delta":{"content":"This is message 14: content: [1987] F430-Passenger car medium-Hummer-Diesel-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":15,"delta":{"content":"This is message 15: content: [1933] Elise/exige-Passenger car light-Lotus-LPG-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":16,"delta":{"content":"This is message 16: content: [1960] Endeavor 2wd-Passenger car compact-Renault-LPG-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":17,"delta":{"content":"This is message 17: content: [2017] L-147/148 Murcielago-Passenger car compact-De Lorean-LPG-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":18,"delta":{"content":"This is message 18: content: [1965] B9 Tribeca Awd-Passenger car mini-Corvette-CNG-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":19,"delta":{"content":"This is message 19: content: [1926] Insight-Passenger car mini-Bugatti-Gasoline-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":20,"delta":{"content":"This is message 20: content: [1999] Limousine-Passenger car heavy-Bentley-CNG-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":21,"delta":{"content":"This is message 21: content: [2019] Montana Sv6 Awd-Passenger car medium-Dino-Methanol-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":22,"delta":{"content":"This is message 22: content: [1931] Passat Wagon 4motion-Passenger car medium-Smart-Diesel-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":23,"delta":{"content":"This is message 23: content: [1915] S4 Avant-Passenger car heavy-Saab-Diesel-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":24,"delta":{"content":"This is message 24: content: [2019] Focus  Fwd-Passenger car medium-Toyota-Methanol-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":25,"delta":{"content":"This is message 25: content: [1979] S40 Awd-Passenger car mini-Farboud-LPG-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":26,"delta":{"content":"This is message 26: content: [1948] Insight-Sport utility vehicle-Tesla-Diesel-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":27,"delta":{"content":"This is message 27: content: [2008] V8 Vantage-Passenger car compact-Lancia-Gasoline-Manual"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":true},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":true}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: {"id":"example-id","object":"chat.completion","created":1722765385,"model":"2024-0618-sensenova","choices":[{"index":28,"delta":{"content":"This is message 28: content: [2016] Slr-Passenger car compact-Citroen-Methanol-Automatic"},"finish_reason":"length","content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"system_fingerprint":"example-fingerprint","prompt_annotations":[{"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":true},"sexual":{"filtered":false},"violence":{"filtered":false}}}],"prompt_filter_results":[{"index":0,"content_filter_results":{"hate":{"filtered":false},"self_harm":{"filtered":false},"sexual":{"filtered":true},"violence":{"filtered":false}}}],"usage":{"prompt_tokens":10,"completion_tokens":20,"total_tokens":30}}

data: [DONE]

###